---
- name: Prepare vagrant nodes
  hosts: all
  become: true
  pre_tasks:

  - name: Set time zone #Указать временную зону
    community.general.timezone:
      name: Europe/Moscow

  - name: Update system cache #обновить системный кеш
    ansible.builtin.apt:
      update_cache: true
      upgrade: true
      cache_valid_time: 3600

  - name: Update all packages to their latest version #обновить пакеты
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Put authorized keys #подложить ключи
    ansible.posix.authorized_key: #эта функция не всегда есть по умолчанию даже если есть установленный ansible; ansible-galaxy collection install ansible.posix - эта команда скачает библиотеку с недостающей функцией
      user: vagrant
      state: present
      key: | #читать как несколько строк; если хотим как разные строки, то не |, а >
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCaYhLm9/X1UKjNsooxXTDIjMPgAu9zrgQU8Nkk+KCyZYNvXmP/QPvrvqSQWtb6N8h20Ae9PCwwOtAcZCtbYOwRC0K3+xdAVdmoBk8BWkAjf/JWNHbXDPFt7DuwzmuDGtUwoGYeukEZ5KT4vN9cpI1whlUJDCHndrPdgGPIbqjchH3UTvdu5sLiKVvmyFaJd1isdQpM1/BBodUVkov/n5P0hwtjmby39XiZg7Z9SY0jivMOuqgeZVNORU3mmdMC8SmxN608M+rBj0uHWCUFNFDObMQRK5gueCicnk7su50H6cJWQwD6dYLd7cByFN7/p2MgsYAcR4xmeWK73I2eZI3JoT23oIfE41shn2jBGOvb2AMVdfqYk0Ytup7G9yJIlxRIN6rplsdC9tV+n/yUp/Efly4OabdOaujGGbfTf6R7aMbaBK8ucEOYtWb3esJBIM9dD58/asEi3Idy9tquPhX/i8wxazn1oscnbD8XL2jcnqKY/iqHGQflm0rTj7tKpKc= rn@srv-rc-11

  - name: install unzip #установить unzip
    ansible.builtin.apt:
      name: unzip

  - name: clone repo #Склонировать репозиторий с конфигами
    ansible.builtin.git:
      repo: https://github.com/nsrusin/otus.git
      dest: /home/vagrant/otus

  - name: copy resolve.conf
    ansible.builtin.copy:
      src: /home/vagrant/otus/resolved.conf
      dest: /etc/systemd/resolved.conf
      remote_src: yes

  - name: restart service systemd-resolved
    service: name=systemd-resolved state=restarted

  - name: Download node_exporter
    ansible.builtin.get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
      dest: /home/vagrant

  - name: Add the user node_exporter
    ansible.builtin.user:
      name: node_exporter
      home: /usr/sbin/false
      shell: /usr/sbin/false

  - name: Create a directory "node_exporter" if it does not exist
    ansible.builtin.file:
      path: /home/vagrant/node_exporter
      state: directory
      mode: '0755'

  - name: Extract node_exporter-1.6.1.linux-amd64.tar.gz into ~/node_exporter
    ansible.builtin.unarchive:
      src: /home/vagrant/node_exporter-1.6.1.linux-amd64.tar.gz
      dest: /home/vagrant/node_exporter
      remote_src: yes

  - name: copy node_exporter file
    ansible.builtin.copy:
      src: /home/vagrant/node_exporter/node_exporter-1.6.1.linux-amd64/node_exporter
      dest: /usr/local/bin/node_exporter
      remote_src: yes
      owner: node_exporter
      group: node_exporter
      mode: '0755'

  - name: copy node_exporter.service file
    ansible.builtin.copy:
      src: /home/vagrant/otus/node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
      remote_src: yes

  - name: Enable service node_exporter
    ansible.builtin.systemd:
      name: node_exporter
      enabled: true

  - name: Start service node_exporter, if not started
    ansible.builtin.service:
      name: node_exporter
      state: started
