---
- name: Prepare web-balance host
  hosts: balance
  become: true
  pre_tasks:
  - name: Install programs
    ansible.builtin.apt:
      name:
        - curl
        - gnupg2
        - ca-certificates
        - lsb-release
        - ubuntu-keyring
      state: latest
      update_cache: yes

  - name: Key import
    shell: 'curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null'

  - name: Add a repo for last version of nginx
    shell: 'echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list'

  - name: Install nginx
    ansible.builtin.apt:
      name:
        - nginx
      state: latest
      update_cache: yes

  - name: Copy balance config
    ansible.builtin.copy:
      src: /home/vagrant/otus/default.conf
      dest: /etc/nginx/conf.d/default.conf
      remote_src: yes

  - name: Test for running nginx
    shell: ps axuf|grep 'nginx'|grep -v "grep" | tr -d "\n" | cat
    register: test_running_nginx
    changed_when: False
    tags: restart-nginx

  - name: First check the configuration
    shell: /usr/sbin/nginx -t
    register: test_nginx_config
    when: test_running_nginx.stdout != ""
    changed_when: False
    ignore_errors: True
    tags: restart-nginx

  - name: Restart nginx
    service: name=nginx state=restarted
    when: test_running_nginx.stdout != "" and test_nginx_config.rc == 0
    tags: restart-nginx

  - name: Start nginx
    service: name=nginx state=started

  - name: dpkg -i filebeat
    ansible.builtin.apt:
      deb: /vagrant/filebeat-8.9.1-amd64.deb

  - name: cp /etc/filebeat/filebeat.yml
    ansible.builtin.copy:
      src: /home/vagrant/otus/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      remote_src: true

  - name: enable module nginx
    shell: "sudo filebeat modules enable nginx"

  - name: sed false to true in /etc/filebeat/modules.d/nginx.yml
    ansible.builtin.replace:
      path: /etc/filebeat/modules.d/nginx.yml
      regexp: 'false'
      replace: 'true'

  - name: sudo filebeat setup
    shell: "sudo filebeat setup"

  - name: start and enable filebeat
    service:
      name: filebeat
      state: started
      enabled: true
