---
- hosts: db
  become: true
  vars:
    mysql_root_password: password

  tasks:
  - name: create user for replication
    mysql_user:
      name: repl
      password: "replrepl"
      #login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:REPLICATION CLIENT"
      host: all

  - name: restart service mysql
    service: name=mysql state=restarted
