---
- hosts: slave
  become: true
  tasks:
  - name: copy config #Скопировать конфиг
    ansible.builtin.copy:
      src: /home/vagrant/otus/mysqld.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      remote_src: yes

  - name: restart mysql #Перезапуск mysql после копирования конфига
    service: name=mysql state=restarted

  - name: Stop mysql replica thread #Stop replica
    community.mysql.mysql_replication:
      mode: stopreplica
      primary_user: repl
      primary_password: replrepl
      login_user: root
      login_password: password
     # channel: mysqld.sock
      login_unix_socket: /run/mysqld/mysqld.sock

  - name: getprimary
    community.mysql.mysql_replication:
      mode: getprimary
      login_user: repl2
      login_password: password
      login_host: 192.168.4.215
    register: Position
     # primary_user: repl
     # primary_password: replrepl
     # login_user: root
     # login_password: password
     # channel: mysqld.sock

#  - name: Use output variable of the previous task (File)
#    debug:
#      "{{ Position.File }}"

#  - name: -"- (Position)
#    debug:
#      msg: "{{ Position.Position }}"



  - name: Change primary server and use binary log with position
    community.mysql.mysql_replication:
      mode: changeprimary
      primary_host: 192.168.4.215
      primary_log_file: "{{ Position.File }}"
      primary_log_pos: "{{ Position.Position }}"
      primary_user: repl
      primary_password: replrepl
      login_user: root
      login_password: password
     # login_host: 192.168.4.216
      login_unix_socket: /run/mysqld/mysqld.sock
     # config_file:

  - name: Start mysql replica thread  #Запустить слейв
    community.mysql.mysql_replication:
      mode: startreplica
      login_unix_socket: /run/mysqld/mysqld.sock
      primary_user: repl
      primary_password: replrepl
      login_user: root
      login_password: password
