# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 min$
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interva$
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this co$
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_exporter DB-02"
    scrape_interval: 5s
    static_configs:
      - targets:
        - "192.168.4.216:9100"

  - job_name: "node_exporter BALANCE"
    scrape_interval: 5s
    static_configs:
      - targets:
        - "192.168.4.212:9100"

  - job_name: "node_exporter WEB-01"
    scrape_interval: 5s
    static_configs:
      - targets:
        - "192.168.4.213:9100"

  - job_name: "node_exporter WEB-02"
    scrape_interval: 5s
    static_configs:
      - targets:
        - "192.168.4.214:9100"

  - job_name: "node_exporter DB-01"
    scrape_interval: 5s
    static_configs:
      - targets:
        - "192.168.4.215:9100"

  - job_name: "node_exporter ELK"
    scrape_interval: 5s
    static_configs:
      - targets:
        - "192.168.4.217:9100"
